version: '3'
services:
  client:
    image: 'aaaknot30/multi-client'
    mem_limit: 128m
    hostname: client
  server:
    image: 'aaaknot30/multi-server'
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
      - NODE_ENV=production
  worker:
    image: 'aaaknot30/multi-worker'
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx:
    image: 'aaaknot30/multi-nginx'
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'
